---
title: "Lit Review"
author: "Villaseñor-Derbez, J.C."
date: "Compiled on `r date()` by `r Sys.info()['user']`"
output:
  bookdown::pdf_document2:
    toc: yes
    toc_depth: 1
    citation_package: biblatex
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}
bibliography: references.bib
---


# \citeauthor{white_2013}

## \citetitle{white_2013}

MPA modeles are often developed at a smaller spatial scale than stock assessments. To date, most MPA works focused on idealized coastlines, with few stie-specific cases. These works often seek to maximize population persistance by selecting number and sizes of reserves, leaving economics on the side.

The paper describes and syntesizes two complementary approaches to including economic and population dunamic factors in the evaluantion of potential MPA networks:

- Static assessment f potential maximum short-term economic impacts that is agnostic to external fishery management and assumes no spillover of fish from reserves to fished areas, or **reallocation of fishing effort**. It does take into account fishing effort, real local catches, and economic values.
- A dynamic bioeconomic model of the long-term equilibrium outcomes that explicitly accounts for fish population dynamics, spillover, **fisher movement**, and fishery management outside the MPAs.

The static analysis provided 4 type of results:

- Percentage of fishing grounds closed, and their value to fisheries, ports, and study region.
- Maximum potential first order economic impacts (worst-case scenarios) at the port-level. (Immediate cost of MPAs)
- An assessment of outliers,fisheries likely to experience disproportionate impacts,measured in terms of significant deviation from other values in thesample.
- Convergence analysis

For the dynamic bioeconomic model, due to the lack of spatially-explicit data on biomass and fishing effort, they focus on the long-term equilibrium, because this level does not depend on the starting conditions. Biomass inside MPAs was compared to a model run with no fishing (i.e. all as MPAs), and yield was compared to a model run with MSY management. These produces two types of results:

- Maps with spatially explicit model outputs
- The second type of result was ranking each MPA proposal ineach evaluation round to compare the overall performance of each metric

- Mention the importance of understanding the level of fishing effort outside the MPAs: "simply observing that a given MPA has not produced an increase in biomass does not reveal what went wrong: was the MPA too small, was enforcement insufficient, wastoo muchfishing allowed outside the MPA, or has insufficient timeelapsed to observe an effect?"
- "This dataset could also be reanalyzed to predict the reallocation offishing effort after implementation: **in theory the fishing fleet should shift effort to the next best set offishing grounds closest to the high value areas now in MPAs**."


# \citeauthor{costello_2010}

## \citetitle{costello_2010}

Previous research focused on the effect of MPAs on limited entry or open access fisheries \footcite{sanchirico_2001,sanchirico_2002,smith_2003}. \citeauthor{smith_2003} find that after accounting for the spatial behavior of fishermen, imposed MPAs lead to a decrease in fishery profits.

Chris models exogenously imposed MPAs on a system already managed by TURFs. They find that:

- Fully coordinated TURFs can include private MPAs, even without government interventions
- Imposing additional MPAs decreases system-wide profits under full coordination
- Abundance will typically increase under exogenous MPA placement in both coordinated and uncoordinated TURF fisheries
- Profits can increase with imposed MPAs in the absence of coordination
- Optimal MPA networks in uncoordinated TURF fisheries may be larger than optimap MPA networks in coordinated TURF fisheries.



























